[[libportaudio]]
arch = "aarch64"
git-tree-sha1 = "d5d55b6f88583fee8731a21534234b2c77e667a9"
libc = "musl"
os = "linux"

    [[libportaudio.download]]
    sha256 = "0bca9d6a3ba5112f640905e4c848af576df1f877a6652761345621184848152f"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.aarch64-linux-musl.tar.gz"
[[libportaudio]]
arch = "i686"
git-tree-sha1 = "061e433da73674192625ec15374961f56843f5e3"
os = "windows"

    [[libportaudio.download]]
    sha256 = "0006266b8d5761096142bcf145c238a342c76270f7be14971a8d6f152fe8b863"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.i686-w64-mingw32.tar.gz"
[[libportaudio]]
arch = "x86_64"
git-tree-sha1 = "aeb5070961b53825bb3e07db7a74609bf927bfdb"
libc = "musl"
os = "linux"

    [[libportaudio.download]]
    sha256 = "c49070b1b3f77c4df6715b33699443b79448fae942b4624ac7bd5354af7a5547"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.x86_64-linux-musl.tar.gz"
[[libportaudio]]
arch = "i686"
git-tree-sha1 = "d934e39dd88d2f463864503a12e085f5eb2076bc"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "b5bff3f701964150d6893740633712f2620f81fc54fa6f3e7811aca0f0e466ae"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.i686-linux-gnu.tar.gz"
[[libportaudio]]
arch = "armv7l"
git-tree-sha1 = "d883cb360c87fb4d540a7a1d97e939f6679a6d60"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "0292638b8bc0107e1b71a969a6313e6aa5ae32954e84a09a99d4531af7ecdce6"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.armv7l-linux-gnueabihf.tar.gz"
[[libportaudio]]
arch = "aarch64"
git-tree-sha1 = "ceb89af1331052ba215f51cead1aca5f2ec005ed"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "492b59bae669f3542d5256973a1115e342d26668078805c890e34836e6fde138"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.aarch64-linux-gnu.tar.gz"
[[libportaudio]]
arch = "x86_64"
git-tree-sha1 = "b8d8165cd3207079948498a0892f410a835bd2ff"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "b61388c9f791735149c8ad158d2cc41e48712b5f2d4fc36f63b9523a9458a917"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.x86_64-linux-gnu.tar.gz"
[[libportaudio]]
arch = "powerpc64le"
git-tree-sha1 = "6bdb24a24e070226ddfe53d95497d6a0311e5508"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "f2fddd90d602c1f50fc9e15b57596fe30bbebecbaab561c554b4cef979bb9607"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.powerpc64le-linux-gnu.tar.gz"
[[libportaudio]]
arch = "x86_64"
git-tree-sha1 = "e9a06f2a75c2207029560e1fc83b1d56963d8335"
os = "macos"

    [[libportaudio.download]]
    sha256 = "61c21b42ab25609b27533f59748bbbefc887a60c86140630a251d03a8614b0d4"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.x86_64-apple-darwin14.tar.gz"
[[libportaudio]]
arch = "x86_64"
git-tree-sha1 = "c6db6a74cb0c839cd108321be295544e74c144db"
os = "freebsd"

    [[libportaudio.download]]
    sha256 = "6ee10bb1544d4f16abe3825122fcb57481b5b273a67283cc3c3294a03a10bc92"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.x86_64-unknown-freebsd11.1.tar.gz"
[[libportaudio]]
arch = "i686"
git-tree-sha1 = "f49bcc9eaba3cf853d17917ada71b6db7bd7eff0"
libc = "musl"
os = "linux"

    [[libportaudio.download]]
    sha256 = "0dbc37c54082588e67ffdcb2ba228f67315c5f17f48e69b7f9873ffd118f8158"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.i686-linux-musl.tar.gz"
[[libportaudio]]
arch = "armv7l"
git-tree-sha1 = "4fae93e081fa9d97b7a9c45cf6496c3686a222b3"
libc = "musl"
os = "linux"

    [[libportaudio.download]]
    sha256 = "c8620718ccbb05c4f1c8b51e7e0f7e066998c05d50df3edbc644193aaefa4ca1"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.armv7l-linux-musleabihf.tar.gz"
[[libportaudio]]
arch = "x86_64"
git-tree-sha1 = "4379f94ecc9d9aee2988676568bcb9e43c4ef00f"
os = "windows"

    [[libportaudio.download]]
    sha256 = "3c4267e4e5fc45e13b7fa6e4a7a6bc9fbb94ed9e2eb20c4ba11b3cb824f9c87c"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.6.0+2/libportaudio.v19.6.0.x86_64-w64-mingw32.tar.gz"
