[[libportaudio]]
arch = "aarch64"
git-tree-sha1 = "313953aa76cf277ab2dfe25fbeace594f2817e02"
os = "macos"

    [[libportaudio.download]]
    sha256 = "e716fe533ebd9b3cb5144560ac533de94b38670e5849112412b9aaca38abb416"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.aarch64-apple-darwin.tar.gz"
[[libportaudio]]
arch = "aarch64"
git-tree-sha1 = "eef3e1195585e789e1675041cf4610c2029b4c19"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "923470580c16f8c42a3dc42db4579fc1dcdabf13d1fee1dba68d5ad1d5681a3b"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.aarch64-linux-gnu.tar.gz"
[[libportaudio]]
arch = "aarch64"
git-tree-sha1 = "986dcd6ddda686dfe18881f738b63f093520191f"
libc = "musl"
os = "linux"

    [[libportaudio.download]]
    sha256 = "6cfa9d254c9068e3ab928478a99f12e33aa83dc9f32020e2883a3c6c84951eca"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.aarch64-linux-musl.tar.gz"
[[libportaudio]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c4ae2c70ce69f752fb0752cd8ae195cc0f2d67ba"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "e1854c4f4c56503c1ba6879a459a53e7e92ae10d53e8f228299ff9e78237e9d2"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.armv6l-linux-gnueabihf.tar.gz"
[[libportaudio]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3a0163d131d08c1366c206adcf7419e303d21ca4"
libc = "musl"
os = "linux"

    [[libportaudio.download]]
    sha256 = "992f56ce269b49c7d3a82a2cf19bffb12dbd7c5275e3b1549c0226c3766848de"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.armv6l-linux-musleabihf.tar.gz"
[[libportaudio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4c6aae18536d644e0c50de1d2fa7699d9b19acc"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "30ed23d0bc620c6b7da42f64f3b31d444493249037fe8e2c0f0e60673ba5279d"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.armv7l-linux-gnueabihf.tar.gz"
[[libportaudio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3e06e8b5a212bccb9fb1a1b5a5b1cd6a8c27b8c2"
libc = "musl"
os = "linux"

    [[libportaudio.download]]
    sha256 = "297e282d6e94efd1dd7822fc2d067860dd449ecb40dfbac7e5f9e786e04653dd"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.armv7l-linux-musleabihf.tar.gz"
[[libportaudio]]
arch = "i686"
git-tree-sha1 = "4ad36fd6b30032a2d323d95aacf97e2aa3324e91"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "f72c4f42ed7473d99588d6ae32429ab4274ec03116be1b6878ca268d94a3ca66"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.i686-linux-gnu.tar.gz"
[[libportaudio]]
arch = "i686"
git-tree-sha1 = "b981601d0cbb89e04cad3f07d034e7f3c87a9852"
libc = "musl"
os = "linux"

    [[libportaudio.download]]
    sha256 = "3dcbb1cacdea9e4d78cde8564ce950e55394f266820633c5181d68e0949c3162"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.i686-linux-musl.tar.gz"
[[libportaudio]]
arch = "i686"
git-tree-sha1 = "eadec4dfdb34d102063a1242162ffbfd9c8686e6"
os = "windows"

    [[libportaudio.download]]
    sha256 = "5fc046a7b5441068c94cde6dbf53f6730c003150ea9619a0f0a5aa56a07ce1c2"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.i686-w64-mingw32.tar.gz"
[[libportaudio]]
arch = "powerpc64le"
git-tree-sha1 = "1de148f618cc1a9ceaee582e1c0e17af20789b1e"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "dc42e7d5e87ce31c22d9b7668139b64dbea89ea5b4f9245df340be2d0a2c935f"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.powerpc64le-linux-gnu.tar.gz"
[[libportaudio]]
arch = "x86_64"
git-tree-sha1 = "806fe9bca585887a50706bc1a3662dc59052d2bd"
os = "macos"

    [[libportaudio.download]]
    sha256 = "225eeb3e2d3079ec9e88205bbe007c53466370e85482326c214b8a9fc85fe1c3"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.x86_64-apple-darwin.tar.gz"
[[libportaudio]]
arch = "x86_64"
git-tree-sha1 = "8ab3ce632a4a052a9031ba158d947df0aba0c948"
libc = "glibc"
os = "linux"

    [[libportaudio.download]]
    sha256 = "a9039229eea13e4c38b71c097a04496e481ee532b52a0d147f2e6fe46958f621"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.x86_64-linux-gnu.tar.gz"
[[libportaudio]]
arch = "x86_64"
git-tree-sha1 = "60a1c20310f22183a5d1c2b18cc72546c7386c7b"
libc = "musl"
os = "linux"

    [[libportaudio.download]]
    sha256 = "fe5c615fca1caebe45eb899027a20f6ef49ab748a2d1bd3499be0b2d817c1429"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.x86_64-linux-musl.tar.gz"
[[libportaudio]]
arch = "x86_64"
git-tree-sha1 = "7cb098ca6cdfe43571cfda056a70c7427d74c176"
os = "freebsd"

    [[libportaudio.download]]
    sha256 = "938ac46b7f8598774f74435331b8d3cd466f7ae8fcbfa6c1ab7e2eb47c117b61"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.x86_64-unknown-freebsd.tar.gz"
[[libportaudio]]
arch = "x86_64"
git-tree-sha1 = "8b3bf9d4098937f5aa12a85f9518523e6b4bfc12"
os = "windows"

    [[libportaudio.download]]
    sha256 = "5de2349a847ada593277cc0879b7b11aee04e82c78c6fc16e8084360578dc7cc"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.x86_64-w64-mingw32.tar.gz"
