# Autogenerated wrapper script for libportaudio_jll for x86_64-w64-mingw32
export libportaudio

JLLWrappers.@generate_wrapper_header("libportaudio")
JLLWrappers.@declare_library_product(libportaudio, "libportaudio.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libportaudio,
        "bin\\libportaudio.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
